### ISSUE TITLE
Find open data sources and submit Project plan

### ISSUE THREAD

**Issue by Ali623** [Ali623/made-template-ws2324#1]
## Tasks
- [ ] Create a public GitHub repository for the module by forking https://github.com/jvalue/2023-amse-template
- [ ] Set up Python / Jayvee / Jupyter Notebook environment
- [ ] Submit project_plan.md
