### ISSUE TITLE
Add Automated Test case for the project

### ISSUE THREAD

**Issue by Ali623** [Ali623/made-template-ws2324#3]
## Tasks
- [ ] Add automated tests for your project
- [ ] Add a /project/tests.sh file that executes your tests
- [ ] There should be at least one test case on the system-test level
- [ ] Executes your data pipeline
- [ ] Validates that the output file(s) are there
